### ISSUE TITLE
InMem, missing docs?

### ISSUE THREAD

**Issue by Yofou** [justwrote/kjob#4]
Correct me if I'm wrong, but I don't see anything mentioned that InMem is not apart of the core libary and needs to be added to your dependcies list (ie, implementation "it.justwrote:kjob-inmem:version" ), just letting you know, so people don't get stuck and give up, and miss out on this amazing libary 😅

**Comment by justwrote** [comment]
Good catch, thanks! You're absolutly right. I forgot to mention this 😅
